export const EMAIL_SERVICE_ID = process.env.NEXT_PUBLIC_EMAIL_SERVICE_ID;
export const EMAIL_CONTACT_TEMPLATE_ID = process.env.NEXT_PUBLIC_EMAIL_CONTACT_TEMPLATE_ID;
export const EMAIL_NEWS_TEMPLATE_ID = process.env.NEXT_PUBLIC_EMAIL_NEWS_TEMPLATE_ID;
export const EMAIL_PUBLIC_KEY = process.env.NEXT_PUBLIC_EMAIL_PUBLIC_KEY;
